name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
             -Dsonar.projectKey=htmlrepo \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
